### PR TITLE
 2 types of banners + Gulp minification with Sass styles

### PR DESCRIPTION
**Pull request by azachar**
orange ribbon for localhost  
and green ribbon for sites that starts with dev., stage., preview. prefix

refactored into an independent self runnable function
refactored css style into a separate file using sass
gulp build process support

### CODE REVIEW

**Comment by brock** [comment]
wow @azachar this is really awesome. I'll have to take a look at this tonight, but just wanted to say thanks right away for all your effort on this. I figured this whole "dev-ribbon" idea was only something I would use, but you've made some really cool improvements and I want to make sure I give them my full attention.

cool

**Comment by azachar** [comment]
Hey @brock, I love that your impl. was really simple, no configuration. Just simple code. 
So I want to keep it that way too. No configuration is needed to use it. Just add a bower dependency and you are done. 

Also using sass and autoprefixer you do not need to specify browser specific css prefixes, it is done out of box :) 

Sure I look forward for your review,

Cheers,
Andy

**Comment by brock** [comment]
Sorry for the delay, but this looks really great @azachar

**Comment by azachar** [comment]
You are welcome :) I am glad that you like it :)

**Pull request merged**
